CREATE TABLE tDoctor(
	ID     BIGINT Primary key,
	SpecID BIGINT NULL,
	CONSTRAINT FkHumanDoct FOREIGN KEY(ID) REFERENCES tHuman(ID) ON DELETE CASCADE,
	CONSTRAINT FkSpecDoct  FOREIGN KEY(SpecID) REFERENCES tSpecialization(ID) ON DELETE SET NULL
);
